version: "3"
services:
  app:
    build: .
    container_name: app
    volumes:
      - ./src:/var/www
    #    entrypoint: entrypoint.sh
    networks:
      - app-network
    depends_on:
      - db
      - redis
  nginx:
    build:
      context: .docker/nginx
      args:
        - HOST_APP=app
        - PORT_APP=9000
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
    networks:
      - app-network
    depends_on:
      - app
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
